[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "https://tom-deluca.netlify.app/*"
  to = "https://tomdeluca.dev/:splat"
  status = 301
  force = true
